T150 契約画面でリフレッシュを配置する。
Lorenzras/kokoas pull request #122
Opened 2022-10-12 06:02 UTC by Lorenzras

## 変更

- react-queryの導入
https://tanstack.com/query/v4/?from=reactQueryV3&original=https://react-query-v3.tanstack.com/

## 理由

- キャッシュが必要になったからです。そして、サーバやり取りの各段階の状態も取得出来るので、いろいろ楽になりました。
- https://trello.com/c/Hib6GspW

2022-10-14 03:55 UTC, RPA02coco commented on src/components/ui/selects/projEstimates/SelectProjEstimates.tsx
> +  const [field, , helpers] = useField(name);
「, ,」→ 誤記でしょうか？

2022-10-17 01:35 UTC, Lorenzras commented on src/components/ui/selects/projEstimates/SelectProjEstimates.tsx
> +  const [field, , helpers] = useField(name);
違和感ありますね。ｗ

FormikのuseFieldの帰り値の型は：

```
useField<any[]>(propsOrFieldName: string | FieldHookConfig<any[]>): [
  FieldInputProps<any[]>, 
  FieldMetaProps<any[]>, 
  FieldHelperProps<any[]>
]
```

配列の分割代入で、以下と同じです。

```
const field = useField(name)[0];
// const meta = useField(name)[1];  真ん中の `FieldMetaProps<any[]>` 必要い　(今のところ)、
const helpers = useField(name)[2];
```

詳しくは
https://ja.javascript.info/destructuring-assignment

2022-10-18 07:37 UTC, Lorenzras commented
![](https://github.trello.services/images/mini-trello-icon.png) [契約画面にリフレッシュボタンを配置する。](https://trello.com/c/Hib6GspW/150-%E5%A5%91%E7%B4%84%E7%94%BB%E9%9D%A2%E3%81%AB%E3%83%AA%E3%83%95%E3%83%AC%E3%83%83%E3%82%B7%E3%83%A5%E3%83%9C%E3%82%BF%E3%83%B3%E3%82%92%E9%85%8D%E7%BD%AE%E3%81%99%E3%82%8B%E3%80%82)

2022-10-19 04:37 UTC, RPA02coco requested changes
「src/hooksQuery/useQueryWithSnack.ts」は空ファイルですが、意図的なものでしょうか？

2022-10-19 09:11 UTC, Lorenzras commented on src/pages/projContracts/hooks/useContractPreview.tsx
> +    setTimeout(() => {
そうです！

タイムアウトの前でもいいですが、そうすると、先にAPIが消費されて、もしユーザが2秒待たずにブラウザー閉じたら無駄になります。

2022-10-19 10:03 UTC, Lorenzras commented on src/pages/projContracts/api/getFormDataId.ts
> +export const getFormDataById = async (
そうですね！「１見積もり＝１契約」が固まっていなかったため、残していました。もう「工事＝契約」に戻ることはなさそうで、**削除します**。

実際、やり方や仕様変更で、こういうファイルがたくさんあります。普段deprecatedを付けて残していますが、やらない時のほうが多いです。ｗ

でも、コンパイルしたコードに含まれないですが、ちゃんとdeprecatedや残す理由をコメントで記載するようにします。

----

関数名の件は、普段「1ページ = 1フォーム=1主Kintoneアプリ」にしていて、各ページにgetFormDataByIdが1個あります。

この「1主Kintoneアプリ」仕様変更でよく変わるものなので、getFormDataByIdに一列にしました。オブジェクト指向の多相性(Polymorphism)の考え方にもなります。

確かに、ページにフォームが複数ある場合、getFormDataByEstimateIdのほうが分かりやすいですね。また、僕は変更のメリットに気づかない点があると思うので、相談させてください。

react-queryに移行に伴い、getFormDataById自体がなくなる方向になるかもしれません。

2022-10-19 23:52 UTC, Lorenzras commented on src/hooksQuery/Readme.md
> +useQueryを理由するhookはここに入れます。
ありがとうございます！修正しました。

2022-10-20 01:46 UTC, RPA02coco commented on src/pages/projContracts/hooks/useContractPreview.tsx
> +    setTimeout(() => {
承知しました！
不安が解消されてすっきりしました。ありがとうございます！

2022-10-20 02:58 UTC, RPA02coco approved these changes
修正確認しました！

2022-10-20 02:58 UTC, merged