単価と金額の算出処理の修正
Lorenzras/kokoas pull request #16
Opened 2022-08-26 03:54 UTC by RPA02coco

**変更**
---

- 単価と金額のフォームに,(カンマ)が入っていたため、削除しnumber型のデータに修正しました。
- 単価と金額の算出処理を修正しました。
　算出に使用する変数の型判定と、想定外の値の場合は'-'(ハイフン)表示にするよう変更しました。

**なぜこの変更をするのか**
---

- 合計値の算出処理に影響が出るため(フォームに格納する値のミスによる)
- 異常値で算出した際、結果が'NaN'と表示される対策

2022-08-26 06:05 UTC, Lorenzras requested changes

2022-08-26 06:05 UTC, Lorenzras commented on src/pages/projEstimate/QuoteTable/RowContent.tsx
> +    setFieldValue(`items[${rowIdx}].unitPrice`, newUnitPrice);
nested ternary (? :) を　if-else に

2022-08-29 01:46 UTC, RPA02coco commented on src/pages/projEstimate/QuoteTable/RowContent.tsx
> +    setFieldValue(`items[${rowIdx}].unitPrice`, newUnitPrice);
if-elseへ修正しました。
ご確認よろしくお願いいたします

2022-08-29 02:42 UTC, Lorenzras approved these changes

2022-08-29 02:42 UTC, Lorenzras commented on src/pages/projEstimate/QuoteTable/RowContent.tsx
> +    setFieldValue(`items[${rowIdx}].unitPrice`, newUnitPrice);
見やすくなりました。ありがとうございます。

2022-08-29 02:42 UTC, Lorenzras commented on src/pages/projEstimate/QuoteTable/RowContent.tsx
> +      }
単純な条件分岐なら、三項演算子(? : )がいいという人もいます。好みの問題ですね。ｗ
ＯＫとします。

```
const totalUnitPrice = newUnitPrice * +quantity;
newPrice = Math.round( tax === '課税' ? totalUnitPrice ) * (1 + (+taxRate / 100)) :  totalUnitPrice ))
```

https://javascript.plainenglish.io/if-else-statements-vs-ternary-operators-in-javascript-d5238af4b516
https://qiita.com/raccy/items/0b25b2f106e2a813828b

2022-08-29 02:43 UTC, merged