37-fix-数値入力用のコンポーネントにおいて、登録型が間違っている
Lorenzras/kokoas pull request #38
Opened 2022-08-31 04:08 UTC by RPA02coco

**変更**
---
FormikInputのsetValueで、入力値をそのまま代入していましたが、
number型に変換してから格納するように変更します。

**なぜ**
---
- Fixes https://github.com/Lorenzras/kokoas/issues/37

ファイル構成変更時に、型変換処理の実装タイミングが被り、
更新が漏れてしまったため、反映します。

2022-08-31 05:22 UTC, Lorenzras requested changes
いいPRです！

次いでに、stringのフィールドにの使えるようにFormikInputのpropに任意のtypeを追加してもらえますか。デフォールトは'string'です。

```
...
export const FormikInput = (
  { name, type = 'string' }:
  { 
    name: string,
    type?: 'string' | 'number' },
) => {
...
```

で、typeは'number'の場合、number型に変換するという仕組みはいかがですか。

2022-08-31 06:06 UTC, RPA02coco commented
承知しました。
確認して対応します。

2022-09-01 01:19 UTC, RPA02coco commented
指摘事項の修正を行いました。
意図とあっていればいいのですが。。。
ご確認おねがいいたします。

2022-09-01 02:14 UTC, Lorenzras approved these changes
完璧です。ありがとうございます。

2022-09-01 02:14 UTC, merged