31 fix improved math processing hayakawa
Lorenzras/kokoas pull request #39
Opened 2022-08-31 04:27 UTC by RPA02coco

運用方法の確認もかねて、Draft pull request試行させていただきます。

2022-09-01 05:42 UTC, Lorenzras commented
関係するIssue
- #31

2022-09-01 06:05 UTC, Lorenzras requested changes
newValuesなどの計算は、useEffectの中に移動出来ると理想ですが、可能でしょうか。

そうなると、計算の回数は減ります。

テーブルを８行ぐらいにして、consoleでテストしました。

`中 <<<` は　useEffect内です。
`外 >>>`　は useEffect外です。

![image](https://user-images.githubusercontent.com/2501255/187851717-bb4f2e31-bded-48bc-843d-c63810412186.png)

2022-09-02 01:09 UTC, RPA02coco commented
承知しました！確認ありがとうございます。
変更できると思いますので、確認して処置します。

2022-09-02 01:42 UTC, RPA02coco commented
処理の修正をしました
ご確認よろしくお願いいたします

2022-09-02 01:47 UTC, Lorenzras requested changes
console.logを削除か、コメントで変えてOKです。

2022-09-02 01:47 UTC, Lorenzras commented on src/pages/projEstimate/hooks/useCalculate.ts
> +    console.log('values', values);
console.logを削除か、コメントで変えてOKです。

2022-09-02 01:50 UTC, RPA02coco commented on src/pages/projEstimate/hooks/useCalculate.ts
> +    console.log('values', values);
失礼しました。
console.logを削除しました。

2022-09-02 01:59 UTC, Lorenzras commented on src/pages/projEstimate/hooks/useCalculate.ts
> +    console.log('values', values);
ありがとうございます！

2022-09-02 02:01 UTC, merged