見積りページにステータスフィールドを追加する
Lorenzras/kokoas pull request #67
Opened 2022-09-12 01:39 UTC by RPA02coco

**変更**
---

- 見積もりページに、ステータスフィールドを追加する

**変更理由**
---

- 仕様変更に伴う対応
- 詳細は[カード参照](https://trello.com/c/McXcRo1G)

2022-09-14 01:09 UTC, Lorenzras requested changes
いい感じです！:rocket: コメントを残しましたので、マージする前に、対応お願いします。:zap:

2022-09-14 01:09 UTC, Lorenzras commented on src/pages/projEstimate/FormProjEstimate.tsx
> +            options={statusChoices.map((c) => ({ label: c, value: c }))}
レンダリングたびに、生成するので、決して変わらないものなら、useMemoやuseCallbackを使うのもいいです。

そして、メニューの生成はFormikStatusの中でいいかもしれません。

2022-09-15 02:07 UTC, RPA02coco commented on src/pages/projEstimate/form.ts
> +  status: '', /* ステータス */
ご指摘ありがとうございます！
空も許す仕様だと思いますので、statusChoiceに空要素を追加してから、form statusにtype定義を追加しました。

2022-09-15 02:45 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/FormikStatus.tsx
> +          field.onChange(event);
指摘事項通り、処理修正に問題ないことを確認しました。
ただし、src/components/ui内、FormikSelectでの実装に切り替えています。

2022-09-15 02:46 UTC, RPA02coco commented on src/pages/projEstimate/FormProjEstimate.tsx
> +            options={statusChoices.map((c) => ({ label: c, value: c }))}
指摘事項通り、useMemoにて実装の確認をし、処理修正に問題ないことを確認しました。
ただし、src/components/ui内、FormikSelectでの実装に切り替えています。

2022-09-15 02:49 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/FormikStatus.tsx
> +    labelMain: string
src/components/ui内、確認させていただきました。
コンポーネントFormikSelectにて実装出来ましたので、こちらに切り替えています。
ご確認をお願い致します。

2022-09-15 03:02 UTC, Lorenzras requested changes

2022-09-15 03:02 UTC, Lorenzras commented on src/pages/projEstimate/FormProjEstimate.tsx
> +            options={statusChoices.map((c) => ({ label: c, value: c }))}
空のストリングは出ないです。

![image](https://user-images.githubusercontent.com/2501255/190303397-d3b1b8b8-a1a7-4bd6-a7d0-904b4601af24.png)

以下のように直せます。

```
options={statusChoices.map((c) => ({ label: c || '-', value: c }))}
```

例として、空のstringの場合、`-`　ですが、　どう表示するか自由です。例えば、`'選択してください'`　などがいいです。

2022-09-15 06:07 UTC, RPA02coco commented
凡ミスすみません。
ご指摘ありがとうございます。
修正しましたので、ご確認をお願いいたします。

2022-09-15 06:15 UTC, Lorenzras approved these changes

2022-09-15 06:15 UTC, merged