フォーム構成の修正
Lorenzras/kokoas pull request #70
Opened 2022-09-12 06:00 UTC by RPA02coco

**変更**
---

- フォームの内容を、必要最低限の要素で再構成する

**変更理由**
---

- #61

2022-09-14 05:18 UTC, Lorenzras requested changes
formのステートが簡潔になりましたね。
マージする前に、コメントの対応お願いします！:zap:

2022-09-15 00:53 UTC, Lorenzras requested changes
内訳でからの行があると、小計欄で、空の行も出ています。
出さない方がいいかな。:low_brightness:

![image](https://user-images.githubusercontent.com/2501255/190287890-f3845a13-00fe-4e55-b400-0b04f9b1b05f.png)

2022-09-15 03:06 UTC, RPA02coco commented on src/pages/projEstimate/hooks/useTotalCalc.ts
> +      taxAmount: acc.taxAmount,
ご指摘ありがとうございます。
例示して頂いた内容で修正します。

2022-09-15 03:07 UTC, RPA02coco commented on src/pages/projEstimate/hooks/useTotalCalc.ts
> +    const taxExcludedAmountVal = ((+cur.costPrice * +cur.quantity) * (1 + (+cur.elemProfRate / 100)));
taxExcludedAmountValの計算、指摘の通りcalcUnitPrice関数の結果に数量(quentity)を掛けたもののため、
処理をまとめて実装しなおします。

2022-09-15 03:08 UTC, RPA02coco commented on src/pages/projEstimate/hooks/useTotalCalc.ts
> +    const taxExcludedAmountVal = ((+cur.costPrice * +cur.quantity) * (1 + (+cur.elemProfRate / 100)));
taxExcludedAmountValですが、calcUnitPrice関数を活用する形で実装しなおします。

2022-09-15 05:10 UTC, RPA02coco commented on src/pages/projEstimate/hooks/useSubTotalCalc.ts
> +    const price = calcPrice(unitPrice, quantity, taxRate, tax);
承知しました！

2022-09-15 05:19 UTC, RPA02coco commented on src/pages/projEstimate/hooks/useTotalCalc.ts
> +    const amountIncludingTaxVal = calcPrice(newUnitPrice, cur.quantity, taxRate, cur.tax);
ありがとうございます。
確かにこの方が分かりやすいので、
「totalAmountInclTax」
「totalAmountExclTax」
で修正します。

2022-09-15 05:26 UTC, RPA02coco commented on src/pages/projEstimate/helpers/calcPrice.ts
> +  if ((unitPrice !== 0) && !(isNaN(quantity))) {
その通りです。すみません、削除します。
ご指摘ありがとうございます。

2022-09-15 05:27 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/Display.tsx
> +      {Math.round(value).toLocaleString()}
承知しました。

2022-09-15 05:37 UTC, RPA02coco commented on src/pages/projEstimate/hooks/useTotalCalc.ts
> +  return Object.entries(result);
ご指摘ありがとうございます。
分割代入で修正しました。

2022-09-15 05:38 UTC, RPA02coco commented on src/pages/projEstimate/SummaryTable/DisplayCellContent.tsx
> +  const dispVal = (name.indexOf('grossProfitMargin')) !== -1 ? (value + ' %')
変更する過程で対応したものでしたが、最終的には変更不要になりました。
旧来の物の方が分かりやすいと思いますので、元に戻します。

2022-09-15 05:48 UTC, RPA02coco commented on src/pages/projEstimate/SummaryTable/DisplayCellContent.tsx
>    name: string,
型定義を追加して対応しました。
ご確認をお願いいたします。

2022-09-15 05:56 UTC, RPA02coco commented
大項目ごとの小計のテーブル表示も含めて、修正しました。
ご確認をお願いいたします。

2022-09-15 06:50 UTC, Lorenzras requested changes
後もう少しです。 🙆‍♂️

2022-09-15 06:50 UTC, Lorenzras commented on src/pages/projEstimate/hooks/useTotalCalc.ts
> +export const useTotalCalc = (): Array<[string, number]> => {
TypeScriptは賢いので実は返り値の型アノテーションを書かなくても勝手に推論してくれます。

```
- export const useTotalCalc = (): Array<[string, number]> => {
+ export const useTotalCalc = () => {
```

2022-09-15 06:50 UTC, Lorenzras commented on src/pages/projEstimate/hooks/useTotalCalc.ts
> +  });
Object.entriesの定義を見ると、どうしても、`[string, T][]`　になります。

`typeof T` を可能にするかtypescriptのコミュニティはまだ議論中です。

取り合えず、型アサーションしましょう。

```
- });
+ }) as Array<[SummaryElem, number]>;
```

2022-09-15 06:50 UTC, Lorenzras commented on src/pages/projEstimate/SummaryTable/SummaryTable.tsx
> +                  <DisplayCellContent name={key} value={value} />
タイプのエラーが出ています。

解消はuseTotalCalcのレビューをご覧ください。

2022-09-16 02:21 UTC, RPA02coco commented on src/pages/projEstimate/hooks/useSubTotalCalc.ts
> +    const price = calcTotalUnitPrice(unitPrice, quantity, taxRate, tax);
口頭で相談した、「grossPrice」で実装します。
また、taxもtaxTypeに修正します。

2022-09-16 02:28 UTC, RPA02coco commented
ご指摘ありがとうございます。
useTotalCalcの指摘事項(2件)の対応により、
SummaryTableのエラーが解消することを確認しました。

2022-09-16 02:31 UTC, Lorenzras approved these changes
OKです。マージお願いします！

2022-09-16 02:55 UTC, merged

2022-09-16 02:57 UTC, RPA02coco commented
ありがとうございます。
対応しました