T122-既存の見積りを選択できるフィールドを設定する
Lorenzras/kokoas pull request #94
Opened 2022-09-22 05:05 UTC by RPA02coco

**変更内容**

見積もりを選択できるフィールドを設定する
既存の見積りの編集を可能にする

---
**変更理由**

[カード#122](https://trello.com/c/gHigda2V)を参照

2022-10-13 06:02 UTC, Lorenzras requested changes
- 「見積もり選択」を押したら、まだ見積もりがない時に何か表示しましょう。
- EstimateInfoはと工事検索と同じ高さでいいかもしれません。

2022-10-14 05:12 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/EstimatesInfo.tsx
> +        </Stack>
承知しました。修正します。

2022-10-14 06:13 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/EstimatesInfo.tsx
> +        </Stack>
修正しました。
ご確認をお願いいたします。

2022-10-14 06:15 UTC, RPA02coco commented
ペアプログラミングで対応した部分と、
別途指摘事項も修正しました。
ご確認をお願いいたします。

2022-10-14 07:51 UTC, Lorenzras requested changes
あともう少しです！:rocket:

2022-10-14 07:51 UTC, Lorenzras commented on src/pages/projEstimate/fieldComponents/EstimatesInfo.tsx
> +      </Typography>
単純にテクストを表示しているようで、Stack無しで、Typography一つでいいかもしれません。

2022-10-14 07:51 UTC, Lorenzras commented on src/pages/projEstimate/fieldComponents/SelectExistEstimates.tsx
> +  const [value, setValue] = useState('');
valueのステート管理はConfirmationDialogRawのみでもいいかもしれません。

2022-10-17 02:14 UTC, Lorenzras requested changes
レビューの続きです。

Dialogの構成はよく出来ていました。
ただ、工事を選択し、Dialogが開かなくても、APIが消費されます。

APIを呼ぶタイミングがDialogを開く時点でエコでしょう。

2022-10-17 02:22 UTC, RPA02coco commented on src/components/ui/selects/projEstimates/SelectProjEstimates.tsx
> +  app?: string,
見積もりでもこのコンポーネントを活用しようとした際に入れて消し忘れていました。
失礼しました。
削除します。

2022-10-17 02:57 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/EstimatesInfo.tsx
> +            widthRatio={75}
widthRatio 削除します！

2022-10-17 02:59 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/EstimatesInfo.tsx
> +      </Typography>
アドバイス頂いた部分も含めて、修正しました。

2022-10-17 03:16 UTC, Lorenzras requested changes
レビューの続きです！よろしくお願いします。

2022-10-17 03:16 UTC, Lorenzras commented on src/pages/projEstimate/fieldComponents/dialogActions/ConfirmationDialogRaw.tsx
> +    onClose(value);
navigateされるので、

onClose()に渡さなくてもいいかもしれません。
よって、SelectExistEstimatesでvalueのステート管理が無くてもいいかな…

将来的に用途あるなら、コメントで残すと嬉しいです。

2022-10-17 03:16 UTC, Lorenzras commented on src/pages/projEstimate/fieldComponents/dialogActions/ListEstimate.tsx
> +export const ListEstimate = ({
Listの一個だと分かるようにListItemEstimateにしましょう。:zap:

2022-10-17 03:16 UTC, Lorenzras commented on src/pages/projEstimate/fieldComponents/dialogActions/ListEstimate.tsx
> +    <Stack width={'100%'} direction={'row'} spacing={1}
`width={'100%'}` が必要ないかもしれません。

2022-10-17 03:16 UTC, Lorenzras commented on src/pages/projEstimate/fieldComponents/dialogActions/ListEstimate.tsx
> +      <Typography variant="body1">
デフォールトは'body1'なので、variantが無くてもいいはずです！

2022-10-17 03:23 UTC, Lorenzras commented on src/pages/projEstimate/fieldComponents/EstimatesInfo.tsx
> +      </Typography>
目が悪いせいで、ラベルとinfoのテクストが同じように見えて、Typography一個でいいと思っちゃいました。ｗ
body1とbody2が実際違いますね。ｗ

この場合、Stackの中に入れた方がいいです。"body1" はデフォールトのようで、variantは無くてもいいです。

2022-10-17 03:26 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/dialogActions/ConfirmationDialogRaw.tsx
> +          Ok
他のココアス仕様と合わせて、「選択」「キャンセル」に修正します。

2022-10-17 05:15 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/dialogActions/ConfirmationDialogRaw.tsx
> +  };
MUIから流用→小変更にしていたため残っていたロジックです。失礼しました。
フォーカスを設定する必要性がない為、関係箇所含めて削除します。

2022-10-17 05:15 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/dialogActions/ConfirmationDialogRaw.tsx
> +  }, [valueProp, open]);
口頭での補足も含め、ありがとうございました。
keepMountedは今回の規模では必要ないだろうということで、keepMountedを削除しました。

2022-10-17 05:17 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/dialogActions/ListEstimate.tsx
> +export const ListEstimate = ({
承知しました！

2022-10-17 05:20 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/dialogActions/ListEstimate.tsx
> +      <Typography variant="body1">
承知しました！
変更前後で差分ないことを確認し、削除しました。

2022-10-17 05:21 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/dialogActions/ListEstimate.tsx
> +    <Stack width={'100%'} direction={'row'} spacing={1}
承知しました。
削除の前後で表示に変更ないことを確認したため、削除しました。

2022-10-17 05:37 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/dialogActions/ConfirmationDialogRaw.tsx
> +    onClose(value);
処理と動作を確認しました。
ご指摘の通り、navigateでの遷移で実装するようにしたため、SelectExistEstimatesでのvalueステート管理は削除できました。
ただ、onClose()がないと、navigateでページ遷移してもダイアログが開いた状態のまま保持されてしまいました。
そのため、handleOk()にはvalueの更新処理は行わずに、onClose()の処理のみ残すようにしました。

ご確認をお願いいたします。

2022-10-17 05:45 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/EstimatesInfo.tsx
> +      </Typography>
承知しました！
なるほど、納得です笑
先ほど確認した内容通り、labelはvariant='caption'、infoはvariantなしで、その他をstackありに巻き戻しました。

2022-10-17 06:03 UTC, RPA02coco commented on src/pages/projEstimate/fieldComponents/SelectExistEstimates.tsx
> +  const { projEstimateRecords } = useEstimateRecords(projId);
かなりヒント頂いたおかげで修正できました。ありがとうございます！
ダイアログの中身のみ、別コンポーネントにして作成しなおして対応しました。

ご確認をお願いいたします。

2022-10-17 06:10 UTC, Lorenzras commented on src/pages/projEstimate/fieldComponents/dialogActions/ConfirmationDialogRaw.tsx
> +    onClose(value);
合ってます！

2022-10-17 06:18 UTC, Lorenzras approved these changes
確認しました！

2022-10-17 06:18 UTC, merged